package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"stacktest/meta"
	"strings"
)

const (
	metaStart = "#meta#"
	metaEnd   = "!meta!"
)

func main() {
	fset := token.NewFileSet()

	var functions []meta.GeneratedEntry
	var files []meta.GeneratedFileEntry

	err := filepath.Walk(
		".",
		func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				switch info.Name() {
				case ".git", "vendor", "cmd":
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".go") {
				return nil
			}
			// skip generated
			if strings.HasSuffix(path, "stackmeta_generated.go") {
				return nil
			}
			// skip tests
			if strings.HasSuffix(path, "_test.go") {
				return nil
			}
			return parseFile(
				fset, path, &functions, &files,
			)
		},
	)

	if err != nil {
		panic(err)
	}

	sort.Slice(
		functions,
		func(i, j int) bool {
			if functions[i].File == functions[j].File {
				return functions[i].Line < functions[j].Line
			}
			return functions[i].File < functions[j].File
		},
	)

	sort.Slice(
		files,
		func(i, j int) bool {
			return files[i].File < files[j].File
		},
	)

	err = generate(functions, files)
	if err != nil {
		panic(err)
	}

	fmt.Printf(
		"stackmeta: generated %d function entries and %d file entries\n",
		len(functions),
		len(files),
	)
}

func parseFile(
	fset *token.FileSet,
	fileName string,
	functions *[]meta.GeneratedEntry,
	files *[]meta.GeneratedFileEntry,
) error {

	src, err := os.ReadFile(fileName)
	if err != nil {
		return err
	}

	file, err := parser.ParseFile(
		fset, fileName, src, parser.ParseComments,
	)
	if err != nil {
		return err
	}
	// file level meta
	if file.Doc != nil {
		if metaValue, ok := parseMeta(file.Doc); ok {
			abs, err := filepath.Abs(fileName)
			if err != nil {
				return err
			}
			*files = append(
				*files, meta.GeneratedFileEntry{File: abs, Meta: metaValue},
			)
		}
	}

	// function metadata
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}
		if fn.Doc == nil {
			continue
		}
		metaValue, ok := parseMeta(fn.Doc)
		if !ok {
			continue
		}
		pos := fset.Position(fn.Pos())
		abs, err := filepath.Abs(fileName)
		if err != nil {
			return err
		}
		*functions = append(
			*functions,
			meta.GeneratedEntry{
				File:     abs,
				Line:     pos.Line,
				Function: fn.Name.Name,
				Meta:     metaValue,
			},
		)
	}
	return nil
}

func parseMeta(group *ast.CommentGroup) (meta.Meta, bool) {
	lines := strings.Split(
		group.Text(), "\n",
	)
	inMeta := false
	metaValue := meta.Meta{Values: make(map[string]string)}

	for _, line := range lines {
		line = strings.TrimSpace(line)

		if line == metaStart {
			inMeta = true
			continue
		}
		if line == metaEnd {
			return metaValue, true
		}
		if !inMeta {
			continue
		}

		parts := strings.SplitN(line, ":", 2)

		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		metaValue.Values[key] = value

		switch key {
		case "service":
			metaValue.Service = value
		case "operation":
			metaValue.Operation = value
		}
	}
	return meta.Meta{}, false
}

func generate(
	functions []meta.GeneratedEntry, files []meta.GeneratedFileEntry,
) error {

	var out strings.Builder

	out.WriteString(`// Code generated by stackmeta-gen; DO NOT EDIT.

	package utils
	
	import "stacktest/meta"
	
	var GeneratedMeta = []meta.GeneratedEntry{
	`)
	for _, entry := range functions {
		out.WriteString("\t{\n")

		fmt.Fprintf(
			&out,
			"\t\tFile: %q,\n",
			entry.File,
		)
		fmt.Fprintf(
			&out,
			"\t\tLine: %d,\n",
			entry.Line,
		)
		fmt.Fprintf(
			&out,
			"\t\tFunction: %q,\n",
			entry.Function,
		)
		out.WriteString("\t\tMeta: meta.Meta{\n")
		fmt.Fprintf(
			&out,
			"\t\t\tService: %q,\n",
			entry.Meta.Service,
		)
		fmt.Fprintf(
			&out,
			"\t\t\tOperation: %q,\n",
			entry.Meta.Operation,
		)
		out.WriteString("\t\t},\n")
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n\n")
	out.WriteString("var GeneratedFileMeta = []meta.GeneratedFileEntry{\n")

	for _, entry := range files {
		out.WriteString("\t{\n")
		fmt.Fprintf(
			&out,
			"\t\tFile: %q,\n",
			entry.File,
		)
		out.WriteString("\t\tMeta: meta.Meta{\n")
		fmt.Fprintf(
			&out,
			"\t\t\tService: %q,\n",
			entry.Meta.Service,
		)
		fmt.Fprintf(
			&out,
			"\t\t\tOperation: %q,\n",
			entry.Meta.Operation,
		)
		out.WriteString("\t\t},\n")
		out.WriteString("\t},\n")
	}
	out.WriteString("}\n")
	filename := filepath.Join("utils", "stackmeta_generated.go")

	return os.WriteFile(filename, []byte(out.String()), 0644)
}
