apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scratch-service-monitor
  labels:
    release: latest
spec:
  endpoints:
    - interval: 5s
      port: metrics
      scrapeTimeout: 4s
  namespaceSelector:
      matchNames:
        - default
  selector:
    matchLabels:
      app: scratch
