{{- if and .Values.securityContext .Values.securityContext.enabled }}
{{- $_ := required "securityContext.runAsUser is required when securityContext.enabled" .Values.securityContext.runAsUser -}}
{{- $_ := required "securityContext.fsGroup is required when securityContext.enabled" .Values.securityContext.fsGroup -}}
{{- if int .Values.securityContext.runAsUser | eq 0 -}}
{{- fail "containers cannot be run as root user." }}
{{- end -}}
{{- end -}}
