// Code generated by stackmeta-gen; DO NOT EDIT.

	package utils
	
	import "stacktest/meta"
	
	var GeneratedMeta = []meta.GeneratedEntry{
		{
		File: "/Users/eugenemartens/Documents/Repos/lab/Go/stack/main.go",
		Line: 27,
		Function: "residentialCall",
		Meta: meta.Meta{
			Service: "residential",
			Operation: "making a call",
		},
	},
	{
		File: "/Users/eugenemartens/Documents/Repos/lab/Go/stack/utils/otherplace.go",
		Line: 8,
		Function: "Test",
		Meta: meta.Meta{
			Service: "other",
			Operation: "",
		},
	},
	{
		File: "/Users/eugenemartens/Documents/Repos/lab/Go/stack/utils/otherplace.go",
		Line: 15,
		Function: "Test2",
		Meta: meta.Meta{
			Service: "another one",
			Operation: "",
		},
	},
}

var GeneratedFileMeta = []meta.GeneratedFileEntry{
	{
		File: "/Users/eugenemartens/Documents/Repos/lab/Go/stack/main.go",
		Meta: meta.Meta{
			Service: "test",
			Operation: "",
		},
	},
}
