apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP #outside world IP reaching type
  ports:
    - protocol: TCP
      port: 80 # outside facing port
      targetPort: 80 # inside/internal pod port (usually 80)
